from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether

ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'output'/'pdf'; OUT.mkdir(parents=True,exist_ok=True)
NAVY=colors.HexColor('#241E17'); PURPLE=colors.HexColor('#5C4A33'); CYAN=colors.HexColor('#5B8DEF'); GREEN=colors.HexColor('#3FA968'); PINK=colors.HexColor('#C7503F'); GOLD=colors.HexColor('#C98A06'); MUTED=colors.HexColor('#6E6353'); LIGHT=colors.HexColor('#FAF6EE'); WHITE=colors.white

DATA={
'en':{
'file':'picas-y-fijas-strategy-guide-en.pdf','header':'PICAS Y FIJAS - STRATEGY GUIDE','title':'Picas y Fijas','subtitle':'Practical strategy guide for codes with 3 to 6 positions','page':'Page',
'idea':'Core idea: a strong guess is not merely one that looks close to the code. It is the guess that eliminates the most possibilities regardless of the answer.',
'intro_h':'What this guide covers','intro':'Strategies for numbers and colors, with and without repeats, recommended openings, clue interpretation, and a systematic method for avoiding contradictions. These are practical heuristics rather than a proof of the absolute minimum number of turns.',
'gold_h':'Golden rule','gold':'After every guess, keep only the codes that would produce exactly the same number of bulls (F) and cows (P) if they were the secret. Choose the next guess to split that remaining set into small groups.',
'terms':[['Concept','Strategic meaning'],['Bull / F','Correct symbol in the correct position.'],['Cow / P','Correct symbol in a different position.'],['0F 0P','Discard every symbol in that guess.'],['F + P','Total number of symbols from the guess that occur in the secret.']],
'method_h':'1. Universal elimination method','steps':[
('1. Explore','Without repeats, open with distinct symbols and cover new symbols. With repeats, include a duplicate early to measure multiplicity.'),('2. Record','Write down the exact F and P result. F+P alone is not enough when position matters.'),('3. Filter','Remove every candidate that fails to reproduce every previous clue.'),('4. Split','If many candidates remain, use a probe that compares positions or introduces new symbols. A probe does not need to be a possible winner.'),('5. Solve','When one or very few candidates remain, play a compatible candidate or the guess that separates them best.')],
'read_h':'How to read a clue','read':[['Answer','Next action'],['0F 0P','Replace all symbols with new ones.'],['0F and several P','The symbols occur, but none is in that position. Reorder them methodically.'],['Several F','Provisionally preserve those positions and change the others to confirm them.'],['F+P below code length','Some symbols are missing; introduce new ones without losing all positional information.']],
'warning':'Do not change every symbol and every position at once after finding matches. Change one controlled element so the new clue remains interpretable.',
'sequence_h':'About 123 - 456 - 789','sequence':'This is a valid coverage strategy for three digits without repeats. F+P tells how many digits from each block belong to the secret. However, it can spend three turns before studying positions, initially omits 0, and may be inefficient with a six-guess limit. Stop as soon as three digits have been located. If 123 gives two matches and 456 gives one, all three digits are already known: do not play 789.',
'no_h':'2. Strategies without repeats','no_intro':'First identify the set of symbols, then determine their positions. Stop introducing symbols once F+P evidence accounts for the whole code.',
'no':[['Positions','Suggested opening','Practical plan'],['3','123; then 456 if needed','Count membership with F+P. Stop at 3 symbols, remember 0, then swap two positions at a time.'],['4','0123','If F+P=4, only order remains. Otherwise replace two symbols with 45, then complete with 67/89 if needed.'],['5','01234','With high F+P, preserve the block and test controlled permutations. With low F+P, replace 2 or 3 symbols with 567.'],['6','012345','Replace groups of two with 67 and then 89. Once six symbols are known, resolve order through swaps.']],
'swap_h':'Swap technique','swap':'Once the symbols are known, swap only two positions. If F rises by two, both positions were corrected; if it falls by two, both were correct before. If it is unchanged, combine that fact with another controlled swap.',
'example_h':'Example: 3 digits without repeats','example':[['Turn','Guess','Clue','Deduction'],['1','123','0F 2P','Two of {1,2,3} occur, both misplaced.'],['2','456','0F 1P','One of {4,5,6} occurs. All three symbols are known; skip 789.'],['3','214','1F 1P','Compare positions of 1 and 2 and test whether 4 is the third symbol.'],['4+','Compatible candidate','-','Only play codes satisfying every clue.']],
'adaptive':'With a short guess limit, the second play must depend on the first clue. A rigid sequence wastes information.',
'rep_h':'3. Strategies with repeats','rep_intro':'You must discover both symbol identity and multiplicity. All-distinct openings are weaker at detecting duplicates.',
'rep':[['Positions','Suggested opening','Purpose'],['3','112','Detect whether 1 repeats while collecting positional information.'],['4','1122','Measure the contribution and multiplicity of two symbols.'],['5','11223','Test two pairs plus one additional symbol.'],['6','112233','Test three pairs, then replace absent pairs with 44/55/66.']],
'mult_h':'Multiplicity test','mult':'Playing one symbol in every position (for example 1111) makes F+P equal its exact multiplicity. This is clear but expensive, so reserve it for likely duplicates or candidates differing only in counts.',
'rep_warn':'With repeats, F+P=2 does not necessarily mean two different symbols; it may be one symbol appearing twice.',
'colors_h':'4. Color games','colors_intro':'The logic is identical. Treat colors as symbols and account for the actual palette size (4, 6, or 8). Smaller palettes make duplicate testing more important.',
'colors':[['Palette','Without repeats','With repeats'],['4 colors','A distinct-color opening covers almost the entire universe for 3 or 4 positions.','For 4 positions use AABB, then CCDD. F+P measures each pair.'],['6 colors','Cover as many different colors as positions; add the remainder only if F+P is incomplete.','Use pairs such as AABB/CDDD or a mixed AABC opening.'],['8 colors','Explore in blocks and stop when total matches fill the code.','Balance new colors with duplicates; do not test all eight unnecessarily.']],
'limits_h':'5. Strategy by guess limit','limits':[['Setting','Priority'],['Unlimited','Maximize certainty; pure presence or multiplicity probes are affordable.'],['10 guesses','Balance: 1-3 exploration turns, then compatible candidates.'],['6 guesses','Every guess should explore while moving toward a solution. Avoid automatic full-alphabet coverage.'],['Timer','Keep a simple guess/F/P table. A perfect strategy that takes too long loses value.']],
'tree_h':'Quick decision tree','tree':[['After a guess','Decision'],['F+P = code length','Introduce no new symbols; solve order and, where applicable, counts.'],['F+P = 0','Replace all symbols.'],['0 < F+P < length','Keep part of the guess and introduce enough new symbols to complete the code.'],['2-5 candidates remain','Choose a guess producing different answers across them, even if it is not a candidate.'],['1 candidate remains','Play it.']],
'errors_h':'Common mistakes','errors':['Repeating a guess that cannot separate candidates.','Ignoring 0 in number mode.','Changing too many positions after several F.','Playing a code that contradicts an earlier clue.','Treating F+P as a count of distinct symbols when repeats are allowed.','Following a fixed sequence after all symbols are already located.'],
'sheet_h':'Tracking sheet','sheet':['Turn','Guess','F','P','F+P','Deduction / remaining candidates'],
'conclusion':'Conclusion: strategies do exist. The strongest practical method treats each clue as a mathematical constraint, removes incompatible candidates, and chooses the next guess for the information it can produce.'},
'fr':{
'file':'guide-strategies-picas-y-fijas-fr.pdf','header':'PICAS Y FIJAS - GUIDE STRATÉGIQUE','title':'Picas y Fijas','subtitle':'Guide pratique pour les codes de 3 à 6 positions','page':'Page',
'idea':'Idée centrale : un bon essai n’est pas seulement proche du code. Il doit éliminer le plus grand nombre de possibilités, quelle que soit la réponse.',
'intro_h':'Contenu du guide','intro':'Stratégies pour les nombres et les couleurs, avec ou sans répétition, ouvertures conseillées, lecture des indices et méthode systématique pour éviter les contradictions. Ce sont des heuristiques pratiques, pas une preuve du nombre minimal absolu de tours.',
'gold_h':'Règle d’or','gold':'Après chaque essai, conserve uniquement les codes qui produiraient exactement le même nombre de F (bien placés) et de P (mal placés) s’ils étaient le secret. Choisis ensuite un essai qui divise ce groupe en petits ensembles.',
'terms':[['Concept','Signification stratégique'],['F / bien placé','Symbole correct à la bonne position.'],['P / mal placé','Symbole correct à une autre position.'],['0F 0P','Écarte tous les symboles de cet essai.'],['F + P','Nombre total de symboles de l’essai présents dans le secret.']],
'method_h':'1. Méthode universelle d’élimination','steps':[
('1. Explorer','Sans répétition, commence avec des symboles distincts. Avec répétition, introduis rapidement un doublon pour mesurer la multiplicité.'),('2. Noter','Écris le résultat exact en F et P. F+P seul ne suffit pas lorsque la position compte.'),('3. Filtrer','Supprime tout candidat qui ne reproduit pas chacun des indices précédents.'),('4. Diviser','S’il reste beaucoup de candidats, compare des positions ou introduis de nouveaux symboles. Un essai de test ne doit pas forcément pouvoir gagner.'),('5. Résoudre','Lorsqu’il reste un ou quelques candidats, joue un candidat compatible ou l’essai qui les sépare le mieux.')],
'read_h':'Comment lire un indice','read':[['Réponse','Action suivante'],['0F 0P','Remplace tous les symboles.'],['0F et plusieurs P','Les symboles sont présents, mais tous mal placés. Réordonne-les méthodiquement.'],['Plusieurs F','Conserve provisoirement ces positions et change les autres pour les confirmer.'],['F+P inférieur à la longueur','Il manque des symboles; introduis-en de nouveaux sans perdre toute l’information de position.']],
'warning':'Ne change pas tous les symboles et toutes les positions après avoir trouvé des correspondances. Modifie un élément contrôlé afin de pouvoir interpréter le nouvel indice.',
'sequence_h':'À propos de 123 - 456 - 789','sequence':'Cette couverture est valable pour trois chiffres sans répétition : F+P indique combien de chiffres de chaque bloc appartiennent au secret. Mais elle peut consommer trois tours avant d’étudier les positions, oublie initialement le 0 et devient coûteuse avec six essais. Arrête dès que trois chiffres sont localisés. Si 123 donne deux correspondances et 456 en donne une, les trois chiffres sont déjà connus : inutile de jouer 789.',
'no_h':'2. Stratégies sans répétition','no_intro':'Identifie d’abord l’ensemble des symboles, puis leurs positions. N’introduis plus de nouveaux symboles dès que les indices F+P couvrent tout le code.',
'no':[['Positions','Ouverture conseillée','Plan pratique'],['3','123, puis 456 si nécessaire','Compte les présences avec F+P. Arrête à 3 symboles, pense au 0, puis permute deux positions.'],['4','0123','Si F+P=4, il ne reste que l’ordre. Sinon remplace deux symboles par 45, puis 67/89 si besoin.'],['5','01234','Avec F+P élevé, conserve le bloc et teste des permutations contrôlées. Sinon remplace 2 ou 3 symboles par 567.'],['6','012345','Remplace des groupes de deux par 67 puis 89. Une fois les six symboles connus, résous l’ordre par permutations.']],
'swap_h':'Technique de permutation','swap':'Lorsque les symboles sont connus, échange seulement deux positions. Si F augmente de deux, les deux positions sont corrigées; s’il baisse de deux, elles étaient correctes avant. Si F ne change pas, combine cette information avec un autre échange contrôlé.',
'example_h':'Exemple : 3 chiffres sans répétition','example':[['Tour','Essai','Indice','Déduction'],['1','123','0F 2P','Deux chiffres de {1,2,3} sont présents, tous deux mal placés.'],['2','456','0F 1P','Un chiffre de {4,5,6} est présent. Les trois sont connus; ne joue pas 789.'],['3','214','1F 1P','Compare les positions de 1 et 2 et teste si 4 est le troisième chiffre.'],['4+','Candidat compatible','-','Ne joue que des codes satisfaisant tous les indices.']],
'adaptive':'Avec peu d’essais, le deuxième coup doit dépendre du premier indice. Une séquence rigide gaspille l’information.',
'rep_h':'3. Stratégies avec répétition','rep_intro':'Il faut trouver les symboles et leur multiplicité. Une ouverture entièrement distincte détecte mal les doublons.',
'rep':[['Positions','Ouverture conseillée','Objectif'],['3','112','Détecter rapidement si 1 se répète tout en testant les positions.'],['4','1122','Mesurer la contribution et la multiplicité de deux symboles.'],['5','11223','Tester deux paires et un symbole supplémentaire.'],['6','112233','Tester trois paires, puis remplacer les paires absentes par 44/55/66.']],
'mult_h':'Test de multiplicité','mult':'Jouer le même symbole partout (par exemple 1111) donne avec F+P sa multiplicité exacte. Ce test est clair mais coûteux; réserve-le aux doublons probables ou aux candidats qui ne différent que par leurs quantités.',
'rep_warn':'Avec répétition, F+P=2 ne signifie pas forcément deux symboles différents : il peut s’agir du même symbole présent deux fois.',
'colors_h':'4. Jeu avec des couleurs','colors_intro':'La logique est identique. Considère les couleurs comme des symboles et tiens compte de la taille de la palette (4, 6 ou 8). Une petite palette rend le test des répétitions plus important.',
'colors':[['Palette','Sans répétition','Avec répétition'],['4 couleurs','Une ouverture avec des couleurs distinctes couvre presque tout l’univers pour 3 ou 4 positions.','Pour 4 positions, joue AABB puis CCDD. F+P mesure chaque paire.'],['6 couleurs','Couvre autant de couleurs distinctes que de positions; ajoute les autres seulement si F+P est incomplet.','Utilise des paires comme AABB/CDDD ou une ouverture mixte AABC.'],['8 couleurs','Explore par blocs et arrête lorsque les correspondances remplissent le code.','Équilibre nouvelles couleurs et doublons; inutile de tester les huit systématiquement.']],
'limits_h':'5. Stratégie selon la limite d’essais','limits':[['Configuration','Priorité'],['Illimité','Maximise la certitude; les tests purs de présence ou de multiplicité sont possibles.'],['10 essais','Équilibre : 1 à 3 tours d’exploration, puis des candidats compatibles.'],['6 essais','Chaque coup doit explorer et avancer vers la solution. Évite de couvrir tout l’alphabet automatiquement.'],['Chronomètre','Tiens un tableau simple essai/F/P. Une stratégie parfaite mais trop lente perd sa valeur.']],
'tree_h':'Arbre de decision rapide','tree':[['Après un essai','Décision'],['F+P = longueur','N’introduis aucun nouveau symbole; résous l’ordre et, si nécessaire, les quantités.'],['F+P = 0','Remplace tous les symboles.'],['0 < F+P < longueur','Conserve une partie de l’essai et introduis assez de nouveaux symboles.'],['Il reste 2 à 5 candidats','Choisis un essai qui donne des réponses différentes entre eux, même s’il n’est pas candidat.'],['Il reste 1 candidat','Joue-le.']],
'errors_h':'Erreurs frequentes','errors':['Repeter un essai incapable de separer les candidats.','Oublier le 0 en mode numérique.','Changer trop de positions après plusieurs F.','Jouer un code qui contredit un indice precedent.','Confondre F+P avec le nombre de symboles distincts lorsque les répétitions sont autorisees.','Suivre une séquence fixe alors que tous les symboles sont déjà localises.'],
'sheet_h':'Feuille de suivi','sheet':['Tour','Essai','F','P','F+P','Déduction / candidats restants'],
'conclusion':'Conclusion : oui, il existe des stratégies. La méthode pratique la plus forte traite chaque indice comme une contrainte mathematique, élimine les candidats incompatibles et choisit le prochain essai selon l’information qu’il peut produire.'}}

def build(lang,d):
    s=getSampleStyleSheet(); s.add(ParagraphStyle(name='T',parent=s['Title'],fontName='Helvetica-Bold',fontSize=25,leading=29,textColor=NAVY,alignment=1,spaceAfter=10)); s.add(ParagraphStyle(name='Sub',parent=s['Normal'],fontSize=11,leading=16,textColor=MUTED,alignment=1,spaceAfter=12)); s.add(ParagraphStyle(name='H1x',parent=s['Heading1'],fontName='Helvetica-Bold',fontSize=18,leading=22,textColor=NAVY,spaceAfter=9)); s.add(ParagraphStyle(name='H2x',parent=s['Heading2'],fontName='Helvetica-Bold',fontSize=13,leading=17,textColor=PURPLE,spaceBefore=6,spaceAfter=4)); s.add(ParagraphStyle(name='B',parent=s['BodyText'],fontSize=9.3,leading=13.5,textColor=NAVY,spaceAfter=5)); s.add(ParagraphStyle(name='Sm',parent=s['BodyText'],fontSize=7.8,leading=10.5,textColor=NAVY)); s.add(ParagraphStyle(name='SmW',parent=s['BodyText'],fontSize=7.8,leading=10.5,textColor=WHITE)); s.add(ParagraphStyle(name='Call',parent=s['BodyText'],fontName='Helvetica-Bold',fontSize=9.7,leading=14,textColor=NAVY))
    def p(x,st='B'): return Paragraph(x,s[st])
    def tbl(rows,widths):
        z=[[p(str(c),'SmW' if i==0 else 'Sm') for c in r] for i,r in enumerate(rows)]; t=Table(z,colWidths=widths,repeatRows=1,hAlign='LEFT'); t.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.45,colors.HexColor('#DDD2C0')),('VALIGN',(0,0),(-1,-1),'TOP'),('BACKGROUND',(0,0),(-1,0),NAVY),('ROWBACKGROUNDS',(0,1),(-1,-1),[WHITE,LIGHT]),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)])); return t
    def box(x,c):
        t=Table([[p(x,'Call')]],colWidths=[174*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.Color(c.red,c.green,c.blue,alpha=.1)),('BOX',(0,0),(-1,-1),1,c),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)])); return t
    def hf(canvas,doc):
        canvas.saveState(); canvas.setFillColor(NAVY); canvas.rect(0,A4[1]-12*mm,A4[0],12*mm,fill=1,stroke=0); canvas.setFillColor(WHITE); canvas.setFont('Helvetica-Bold',8); canvas.drawString(18*mm,A4[1]-8*mm,d['header']); canvas.setFillColor(MUTED); canvas.setFont('Helvetica',8); canvas.drawRightString(A4[0]-8*mm,9*mm,f"{d['page']} {doc.page}"); canvas.restoreState()
    story=[Spacer(1,18*mm),p(d['title'],'T'),p(d['subtitle'],'Sub'),box(d['idea'],GREEN),Spacer(1,6*mm),p(d['intro_h'],'H1x'),p(d['intro']),p(d['gold_h'],'H2x'),p(d['gold']),tbl(d['terms'],[38*mm,136*mm]),PageBreak(),p(d['method_h'],'H1x')]
    for a,b in d['steps']: story.append(KeepTogether([p(a,'H2x'),p(b)]))
    story += [p(d['read_h'],'H2x'),tbl(d['read'],[43*mm,131*mm]),box(d['warning'],GOLD),p(d['sequence_h'],'H2x'),p(d['sequence']),PageBreak(),p(d['no_h'],'H1x'),p(d['no_intro']),tbl(d['no'],[22*mm,43*mm,109*mm]),p(d['swap_h'],'H2x'),p(d['swap']),p(d['example_h'],'H2x'),tbl(d['example'],[15*mm,28*mm,32*mm,99*mm]),box(d['adaptive'],PINK),PageBreak(),p(d['rep_h'],'H1x'),p(d['rep_intro']),tbl(d['rep'],[25*mm,40*mm,109*mm]),p(d['mult_h'],'H2x'),p(d['mult']),box(d['rep_warn'],GOLD),p(d['colors_h'],'H1x'),p(d['colors_intro']),tbl(d['colors'],[25*mm,74*mm,75*mm]),PageBreak(),p(d['limits_h'],'H1x'),tbl(d['limits'],[42*mm,132*mm]),p(d['tree_h'],'H2x'),tbl(d['tree'],[55*mm,119*mm]),p(d['errors_h'],'H2x')]
    story += [p('• '+x) for x in d['errors']]
    rows=[d['sheet']]+[[str(i),'','','','',''] for i in range(1,6)]
    story += [p(d['sheet_h'],'H2x'),tbl(rows,[14*mm,28*mm,12*mm,12*mm,16*mm,92*mm]),Spacer(1,4*mm),box(d['conclusion'],GREEN)]
    path=OUT/d['file']; doc=SimpleDocTemplate(str(path),pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=20*mm,bottomMargin=20*mm,title=d['subtitle'],author='Picas y Fijas'); doc.build(story,onFirstPage=hf,onLaterPages=hf); print(path)

for lang,data in DATA.items(): build(lang,data)
